require File.dirname(__FILE__) + '/ocrunner/console'
require File.dirname(__FILE__) + '/ocrunner/cli'
require File.dirname(__FILE__) + '/ocrunner/test_case'
require File.dirname(__FILE__) + '/ocrunner/test_error'
require File.dirname(__FILE__) + '/ocrunner/test_suite'
require File.dirname(__FILE__) + '/ocrunner/parse_machine'
require File.dirname(__FILE__) + '/ocrunner/output_processor'
require File.dirname(__FILE__) + '/ocrunner/test_runner'