require File.dirname(__FILE__) + '/ocrunner/cli'
require File.dirname(__FILE__) + '/ocrunner/console'
require File.dirname(__FILE__) + '/ocrunner/test_case'
require File.dirname(__FILE__) + '/ocrunner/test_suite'
require File.dirname(__FILE__) + '/ocrunner/test_runner'